<?php

namespace Database\Seeders;

use App\Models\Formation;
use Illuminate\Database\Seeder;

class FormationsCatalogSeeder extends Seeder
{
    /**
     * Aligns the training catalogue with the official EEHT programme dossier:
     * CAP Restauration, BEP Restauration, BEP Réceptionniste, BT Restauration,
     * BTS Tourisme, DTS Tourisme, DTS Restauration, Tourisme Durable,
     * Technique de Guidage, Formation courte en Restauration, Agent de
     * Caisse, Chef de Rang, Certificats de Spécialité (Pâtisserie, Cuisine,
     * Restauration), Barista.
     */
    public function run(): void
    {
        // Placeholder formations with no linked students/classes/subjects — safe to retire.
        Formation::whereIn('code', ['CAP-CUIS', 'CAP-REST', 'DTS-MH'])->delete();

        $catalog = [
            [
                'name' => 'CAP Restauration',
                'code' => 'CAP-REST',
                'diploma' => 'CAP',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Niveau 4ème',
                'duration' => '3 ans',
                'description' => "Le Certificat d'Aptitude Professionnelle (CAP) Restauration est une formation professionnelle destinée aux apprenants souhaitant acquérir les compétences de base nécessaires pour travailler dans les métiers de la restauration.\n\nLa formation permet notamment de maîtriser les techniques fondamentales de préparation culinaire, de service en salle, de mise en place, d'accueil de la clientèle ainsi que les règles d'hygiène, de sécurité alimentaire et d'organisation du travail.\n\nL'apprenant est préparé à évoluer dans un environnement professionnel tel qu'un restaurant, un hôtel, une cantine, un service traiteur ou toute autre structure de restauration.",
                'admission_conditions' => "• Avoir atteint la classe de 4ème (ou un niveau scolaire équivalent)\n• Être motivé par les métiers de la restauration\n• Satisfaire aux conditions d'inscription fixées par l'établissement\n• Présenter les pièces administratives demandées\n• Pour les candidats suivant la voie des examens d'État, respecter les conditions fixées par les autorités compétentes",
                'program' => "ENSEIGNEMENTS PROFESSIONNELS\n• Technologie professionnelle de la restauration\n• Techniques culinaires\n• Cuisine sénégalaise et internationale\n• Techniques de préparation et de cuisson\n• Service en salle\n• Art de la table\n• Mise en place et dressage\n• Hygiène et sécurité alimentaire\n• Sciences appliquées à l'alimentation\n• Connaissance des produits alimentaires\n\nENSEIGNEMENTS GÉNÉRAUX\n• Communication professionnelle\n• Français\n• Mathématiques appliquées\n• Informatique\n• Anglais professionnel\n• Éducation civique et professionnelle\n• Entrepreneuriat\n\nFORMATION PRATIQUE\n• Travaux pratiques\n• Stage professionnel",
                'objectives' => "• Participer à la préparation et à la production des repas\n• Appliquer les techniques culinaires de base\n• Réaliser la mise en place d'un service\n• Accueillir et servir les clients\n• Respecter les règles d'hygiène et de sécurité\n• Utiliser correctement le matériel professionnel\n• Travailler efficacement en équipe\n• S'intégrer dans une structure professionnelle de restauration",
                'career_prospects' => "• Commis de cuisine\n• Aide-cuisinier\n• Commis de restaurant\n• Serveur ou serveuse\n• Employé polyvalent de restauration\n• Agent de restauration collective\n• Employé de service dans un hôtel\n• Employé dans une entreprise de restauration ou de traiteur\n\nPoursuite d'études possible vers le BEP Restauration selon les conditions d'admission.",
                'order' => 1,
            ],
            [
                'name' => 'BEP Restauration',
                'code' => 'BEP-REST',
                'diploma' => 'BEP',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'BFEM',
                'duration' => '2 ans',
                'description' => "Le Brevet d'Études Professionnelles (BEP) Restauration est une formation professionnalisante permettant d'approfondir les compétences dans les domaines de la cuisine, du restaurant et du service.\n\nElle prépare les apprenants à maîtriser les différentes étapes de la production et du service en restauration, depuis l'organisation du poste de travail jusqu'à la satisfaction du client.\n\nLa formation accorde une place importante aux travaux pratiques et aux situations réelles de production, ainsi qu'au développement des connaissances en gestion, communication, hygiène et organisation professionnelle.",
                'admission_conditions' => "• Être titulaire du BFEM, du CAP correspondant ou d'un diplôme admis en équivalence, selon la voie de formation\n• Posséder un niveau scolaire compatible avec la formation\n• Satisfaire aux conditions administratives fixées par l'établissement et les autorités compétentes\n• Être apte à suivre les activités pratiques liées aux métiers de la restauration",
                'program' => "ENSEIGNEMENTS PROFESSIONNELS\n• Technologie culinaire\n• Techniques de cuisine\n• Cuisine sénégalaise, africaine et internationale\n• Pâtisserie de base\n• Techniques de restaurant\n• Service des mets et boissons\n• Art de la table\n• Organisation du travail\n• Gestion des approvisionnements\n• Connaissance des produits\n• Hygiène et sécurité alimentaire\n• Prévention des risques professionnels\n\nENSEIGNEMENTS GÉNÉRAUX ET APPLIQUÉS\n• Français\n• Anglais professionnel\n• Mathématiques appliquées\n• Sciences appliquées\n• Informatique\n• Communication professionnelle\n• Économie et gestion\n• Entrepreneuriat\n• Droit et législation professionnelle\n• Éducation civique\n\nFORMATION PRATIQUE\n• Travaux pratiques de cuisine et de restaurant\n• Simulations professionnelles\n• Études de cas\n• Stage en entreprise",
                'objectives' => "• Réaliser des productions culinaires de qualité\n• Organiser et gérer son poste de travail\n• Assurer un service professionnel en salle\n• Maîtriser les techniques de dressage et de présentation\n• Appliquer les normes d'hygiène et de sécurité\n• Participer à la gestion des matières premières\n• Communiquer avec la clientèle et les équipes\n• Développer son autonomie professionnelle",
                'career_prospects' => "• Cuisinier débutant\n• Commis de cuisine qualifié\n• Employé qualifié de restauration\n• Serveur qualifié\n• Chef de rang débutant\n• Employé de restaurant\n• Employé polyvalent d'hôtel\n• Agent de restauration collective\n• Employé chez un traiteur\n\nPoursuite d'études possible vers le BT Restauration ou d'autres formations compatibles.",
                'order' => 2,
            ],
            [
                'name' => 'BEP Réceptionniste',
                'code' => 'BEP-RECEP',
                'diploma' => 'BEP',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'BFEM',
                'duration' => '2 ans',
                'description' => "Le BEP Réceptionniste prépare les apprenants aux métiers de l'accueil et de la réception dans les établissements hôteliers et touristiques.\n\nLe réceptionniste représente l'un des principaux interlocuteurs du client : il assure l'accueil, l'information, l'enregistrement, l'orientation et le suivi du séjour des clients.\n\nLa formation permet de développer les compétences en communication, accueil, langues étrangères, outils informatiques et organisation des activités de réception.",
                'admission_conditions' => "• Être titulaire du BFEM, d'un diplôme professionnel correspondant ou d'un diplôme admis en équivalence\n• Posséder les aptitudes nécessaires à la communication et à l'accueil\n• Être motivé par les métiers de l'hôtellerie\n• Satisfaire aux conditions administratives de l'établissement",
                'program' => "ENSEIGNEMENTS PROFESSIONNELS\n• Techniques d'accueil et de réception\n• Gestion des réservations\n• Enregistrement et départ des clients\n• Relation clientèle\n• Communication professionnelle et correspondance commerciale\n• Organisation d'un établissement hôtelier\n• Initiation à la gestion hôtelière\n• Utilisation des logiciels de réception\n• Gestion des réclamations\n\nLANGUES ET COMMUNICATION\n• Français professionnel\n• Anglais hôtelier\n• Communication orale et écrite\n• Techniques de vente\n• Accueil d'une clientèle nationale et internationale\n\nENSEIGNEMENTS COMPLÉMENTAIRES\n• Informatique\n• Mathématiques appliquées\n• Économie et gestion\n• Hygiène et sécurité\n• Législation professionnelle\n• Entrepreneuriat\n• Culture touristique\n• Stage professionnel",
                'objectives' => "• Accueillir et orienter les clients\n• Gérer les réservations\n• Effectuer les opérations d'arrivée et de départ\n• Communiquer efficacement avec la clientèle\n• Utiliser les outils informatiques professionnels\n• Gérer les informations liées au séjour des clients\n• Répondre aux demandes et réclamations\n• Contribuer à l'image et à la qualité de service d'un établissement",
                'career_prospects' => "• Réceptionniste\n• Agent d'accueil\n• Agent de réservation\n• Employé de réception\n• Standardiste\n• Assistant réception\n• Agent d'information touristique\n• Employé polyvalent dans un hôtel ou une résidence touristique",
                'order' => 3,
            ],
            [
                'name' => 'BT Restauration',
                'code' => 'BT-REST',
                'diploma' => 'BT',
                'diploma_recognition' => "Diplôme d'école (validé par la Chambre des Métiers)",
                'level' => 'BEP',
                'duration' => '3 ans',
                'description' => "Le Brevet de Technicien (BT) Restauration est une formation de niveau supérieur au BEP permettant de former des techniciens capables d'exercer des responsabilités plus importantes dans la production culinaire, le restaurant et l'organisation d'un service.\n\nLa formation développe à la fois les compétences techniques, organisationnelles et managériales : l'apprenant est préparé à superviser une équipe, organiser une activité de restauration, contrôler la qualité des prestations et participer à la gestion d'un établissement.",
                'admission_conditions' => "• Être titulaire du BEP correspondant, du BFEM avec le niveau ou parcours exigé, ou d'un diplôme admis en équivalence selon les modalités d'accès\n• Répondre aux conditions fixées pour la formation concernée\n• Posséder de bonnes bases en restauration et dans les matières générales",
                'program' => "DOMAINE PROFESSIONNEL\n• Technologie de la restauration\n• Techniques culinaires avancées\n• Cuisine nationale et internationale, gastronomie, pâtisserie\n• Organisation de la production\n• Techniques de restaurant et art de la table\n• Œnologie et connaissance des boissons\n• Gestion des approvisionnements et des stocks\n• Contrôle de la qualité\n• Hygiène, sécurité et HACCP\n• Management d'équipe\n\nGESTION ET ADMINISTRATION\n• Économie, gestion hôtelière et restauration\n• Comptabilité de base et calcul des coûts\n• Gestion des achats et contrôle budgétaire\n• Marketing et techniques de vente\n• Création et gestion d'entreprise\n\nENSEIGNEMENTS GÉNÉRAUX\n• Français\n• Anglais professionnel\n• Mathématiques appliquées\n• Informatique\n• Communication professionnelle\n• Droit et législation\n• Entrepreneuriat\n\nPROFESSIONNALISATION\n• Travaux pratiques et projets professionnels\n• Études de cas et visites pédagogiques\n• Stage en entreprise",
                'objectives' => "• Organiser une activité de restauration\n• Superviser la production culinaire\n• Contrôler la qualité des prestations\n• Encadrer une équipe\n• Participer à la gestion d'un restaurant\n• Gérer les approvisionnements et les stocks\n• Calculer les coûts et contribuer à la rentabilité\n• Appliquer les normes d'hygiène et de sécurité\n• Développer un projet entrepreneurial dans la restauration",
                'career_prospects' => "• Technicien en restauration\n• Chef de cuisine adjoint\n• Chef de partie\n• Responsable de salle\n• Maître d'hôtel débutant\n• Responsable d'unité de restauration\n• Responsable de production\n• Gestionnaire de restaurant\n• Responsable de service traiteur\n• Entrepreneur dans la restauration",
                'order' => 4,
            ],
            [
                'name' => 'BTS Tourisme',
                'code' => 'BTS-TOUR',
                'diploma' => 'BTS',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Baccalauréat',
                'duration' => '2 ans',
                'description' => "Le Brevet de Technicien Supérieur (BTS) Tourisme est une formation d'enseignement supérieur professionnel destinée à former des techniciens supérieurs capables de participer à la conception, à la commercialisation et à la gestion de produits et services touristiques.\n\nLa formation prépare aux métiers des agences de voyages, offices de tourisme, structures d'hébergement, entreprises de loisirs, transport touristique et organisations de promotion touristique.",
                'admission_conditions' => "• Être titulaire du Baccalauréat ou d'un diplôme admis en équivalence\n• Ou être titulaire d'un diplôme professionnel permettant l'accès au niveau BTS selon la réglementation applicable\n• Satisfaire aux conditions d'admission de l'établissement\n• Présenter un dossier complet",
                'program' => "ENSEIGNEMENTS TOURISTIQUES\n• Introduction au tourisme, géographie touristique\n• Patrimoine culturel et naturel, destinations touristiques\n• Techniques de production et de conception de produits touristiques\n• Techniques de vente, gestion des agences de voyages\n• Billetterie et réservation\n• Marketing touristique et promotion des destinations\n• Animation touristique, gestion des événements\n• Tourisme durable, législation touristique\n\nGESTION ET MANAGEMENT\n• Gestion des entreprises touristiques\n• Comptabilité et gestion financière\n• Gestion des ressources humaines\n• Management, économie et droit du tourisme\n• Entrepreneuriat\n\nCOMMUNICATION ET LANGUES\n• Français professionnel\n• Anglais touristique\n• Communication professionnelle et techniques de négociation\n• Informatique et outils numériques du tourisme\n\nPROFESSIONNALISATION\n• Études de cas, projet touristique\n• Travaux pratiques, visites professionnelles\n• Stage en entreprise\n• Mémoire ou projet de fin de formation",
                'objectives' => "• Concevoir et commercialiser des produits touristiques\n• Accueillir, informer et conseiller les touristes\n• Organiser des voyages et circuits\n• Participer à la promotion d'une destination\n• Gérer les opérations d'une agence de voyages\n• Utiliser les outils numériques de réservation et de gestion\n• Développer des activités touristiques durables\n• Participer à la gestion d'une entreprise touristique",
                'career_prospects' => "• Technicien supérieur en tourisme\n• Agent de voyages, conseiller en voyages\n• Agent de réservation\n• Chargé de production ou de développement touristique\n• Guide touristique, selon les qualifications et autorisations requises\n• Agent d'accueil touristique\n• Chargé de promotion touristique, assistant marketing touristique\n• Organisateur d'événements\n• Entrepreneur dans le secteur touristique",
                'order' => 5,
            ],
            [
                'name' => 'DTS Tourisme',
                'code' => 'DTS-TOUR',
                'diploma' => 'DTS',
                'diploma_recognition' => "Diplôme d'école",
                'level' => 'Baccalauréat',
                'duration' => '2 ans',
                'description' => "Le Diplôme de Technicien Supérieur (DTS) Tourisme est une formation supérieure professionnelle orientée vers l'acquisition de compétences techniques, managériales et opérationnelles dans le domaine du tourisme.\n\nCette formation permet de développer une expertise dans la gestion des entreprises touristiques, la conception de produits et circuits, la commercialisation, la promotion des destinations et le management des services touristiques, avec une place importante accordée à la professionnalisation, aux outils numériques, aux langues étrangères et à l'expérience en entreprise.",
                'admission_conditions' => "• Être titulaire du Baccalauréat ou d'un diplôme reconnu équivalent\n• Répondre aux conditions particulières fixées par l'établissement\n• Posséder un intérêt pour les métiers du tourisme, de la communication et de la gestion\n• Déposer un dossier d'admission complet",
                'program' => "TOURISME ET DÉVELOPPEMENT\n• Fondamentaux du tourisme, géographie touristique\n• Patrimoine et culture, développement touristique\n• Tourisme durable et responsable, aménagement touristique\n• Gestion des destinations, études des marchés touristiques\n\nPRODUCTION ET COMMERCIALISATION\n• Production de voyages, conception de circuits touristiques\n• Techniques de vente, gestion des agences de voyages\n• Réservation et billetterie\n• Marketing touristique, marketing digital et e-tourisme\n• Relation client\n\nMANAGEMENT ET GESTION\n• Management des organisations touristiques\n• Gestion financière, comptabilité, contrôle de gestion\n• Gestion des ressources humaines\n• Droit et économie du tourisme\n• Gestion de projet, entrepreneuriat\n\nCOMMUNICATION\n• Français professionnel, anglais touristique\n• Communication professionnelle et digitale\n• Techniques de négociation\n• Informatique et outils professionnels\n\nPROFESSIONNALISATION\n• Projet tutoré, études de cas, séminaires professionnels\n• Visites d'entreprises\n• Stage professionnel, rapport ou mémoire de stage\n• Soutenance finale",
                'objectives' => "• Analyser le marché touristique\n• Concevoir des produits et services touristiques\n• Organiser et commercialiser des voyages\n• Gérer une activité ou une entreprise touristique\n• Promouvoir les destinations et patrimoines\n• Élaborer des stratégies marketing\n• Utiliser les technologies numériques du tourisme\n• Gérer des projets touristiques\n• Créer et développer une entreprise dans le secteur touristique",
                'career_prospects' => "• Technicien supérieur en tourisme\n• Responsable d'agence de voyages\n• Chargé de production ou de réservation touristique\n• Responsable commercial tourisme\n• Chargé de marketing touristique\n• Responsable d'accueil touristique\n• Chargé de développement touristique\n• Assistant chef de projet touristique\n• Gestionnaire de structure touristique\n• Consultant junior en tourisme\n• Entrepreneur touristique",
                'order' => 6,
            ],
            [
                'name' => 'DTS Restauration',
                'code' => 'DTS-REST',
                'diploma' => 'DTS',
                'diploma_recognition' => "Diplôme d'école",
                'level' => 'BEP ou BT',
                'duration' => '2 ans',
                'description' => "Le Diplôme de Technicien Supérieur (DTS) Restauration est une formation de perfectionnement destinée aux apprenants disposant déjà d'une base solide en restauration (BEP ou BT) et souhaitant approfondir leur expertise technique, organisationnelle et managériale.\n\nLa formation prépare à la prise de responsabilités dans la gestion d'un établissement de restauration : organisation de la production, gestion des stocks et des approvisionnements, maîtrise des coûts, management d'équipe et développement d'un projet entrepreneurial dans le secteur.",
                'admission_conditions' => "• Être titulaire du BEP Restauration, du BT Restauration ou d'un diplôme admis en équivalence\n• Posséder une première expérience ou une bonne maîtrise des techniques de base de la restauration\n• Satisfaire aux conditions administratives fixées par l'établissement\n• Déposer un dossier d'admission complet",
                'program' => "ORGANISATION ET PRODUCTION\n• Techniques de restauration avancées\n• Organisation d'un établissement\n• Organisation de la production\n• Contrôle de la qualité\n• Hygiène, sécurité et HACCP\n\nGESTION\n• Gestion des stocks et approvisionnement\n• Gestion des coûts et calcul des prix\n• Comptabilité de base\n• Management d'équipe\n\nDÉVELOPPEMENT PROFESSIONNEL\n• Relation clientèle\n• Communication professionnelle\n• Entrepreneuriat\n• Création et gestion d'entreprise\n\nPROFESSIONNALISATION\n• Études de cas et projets professionnels\n• Stage en entreprise",
                'objectives' => "• Organiser la production et le service d'un établissement de restauration\n• Gérer les stocks et les approvisionnements\n• Maîtriser les coûts et contribuer à la rentabilité\n• Encadrer et animer une équipe\n• Développer la relation avec la clientèle\n• Participer à la gestion administrative et financière d'un établissement\n• Construire un projet entrepreneurial dans la restauration",
                'career_prospects' => "• Responsable de restauration\n• Assistant manager\n• Responsable de service\n• Gestionnaire d'établissement\n• Chef de partie\n• Responsable de production\n• Entrepreneur dans la restauration",
                'order' => 7,
            ],
            [
                'name' => 'Tourisme Durable',
                'code' => 'TOUR-DURABLE',
                'diploma' => null,
                'specialty_override' => 'Tourisme Durable',
                'diploma_recognition' => 'Attestation',
                'level' => 'Baccalauréat',
                'duration' => '1 an',
                'description' => "Le Tourisme Durable s'adresse aux passionnés de tourisme souhaitant s'investir dans des pratiques qui valorisent les territoires, les ressources, le patrimoine et les communautés locales.\n\nLa formation associe apprentissage théorique et expérience de terrain, avec une forte dimension pratique consacrée à la conception d'activités touristiques respectueuses de l'environnement et des populations locales.",
                'admission_conditions' => "• Être titulaire du Baccalauréat ou d'un diplôme admis en équivalence\n• Avoir un intérêt marqué pour le tourisme, l'environnement et le développement local\n• Être disponible pour les phases de travail de terrain\n• Déposer un dossier d'admission complet",
                'program' => "TOURISME ET TERRITOIRES\n• Principes du tourisme durable\n• Valorisation du patrimoine\n• Développement local\n• Écotourisme\n• Ressources locales et environnement\n\nCONCEPTION ET PROMOTION\n• Conception d'activités touristiques\n• Communication touristique\n• Marketing touristique\n\nTERRAIN\n• Travail de terrain\n• Projets tutorés\n• Visites et études de cas",
                'objectives' => "• Comprendre les enjeux du tourisme durable et responsable\n• Valoriser le patrimoine et les ressources locales\n• Concevoir des activités touristiques respectueuses de l'environnement\n• Mobiliser les communautés locales dans un projet touristique\n• Communiquer et promouvoir une destination durable\n• Conduire un projet de terrain de bout en bout",
                'career_prospects' => "• Agent de développement touristique\n• Animateur touristique\n• Chargé de projet\n• Agent d'écotourisme\n• Entrepreneur touristique",
                'order' => 8,
            ],
            [
                'name' => 'Technique de Guidage',
                'code' => 'GUIDAGE',
                'diploma' => null,
                'specialty_override' => 'Technique de Guidage',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Baccalauréat',
                'duration' => '1 an',
                'description' => "La formation Technique de Guidage prépare les apprenants à accompagner, informer et encadrer les visiteurs lors de circuits, excursions et découvertes touristiques.\n\nOrganisée en deux temps — six mois de cours suivis de six mois de terrain — elle permet de transformer une passion pour la découverte et le patrimoine en compétence professionnelle reconnue, sanctionnée par un diplôme d'État.",
                'admission_conditions' => "• Être titulaire du Baccalauréat ou d'un diplôme admis en équivalence\n• Avoir un bon niveau d'expression orale et le goût du contact avec le public\n• Être disponible pour la phase de terrain de six mois\n• Déposer un dossier d'admission complet",
                'program' => "CONNAISSANCES TOURISTIQUES\n• Histoire et culture\n• Géographie touristique\n• Présentation du patrimoine\n\nTECHNIQUES DE GUIDAGE\n• Techniques de guidage\n• Accueil des visiteurs\n• Animation touristique\n• Organisation d'excursions\n• Construction d'itinéraires\n• Gestion des groupes\n\nCOMMUNICATION\n• Prise de parole\n• Communication professionnelle\n• Accompagnement des visiteurs\n\nTERRAIN (6 MOIS)\n• Mise en pratique des connaissances acquises\n• Accompagnement de circuits réels\n• Encadrement de groupes de visiteurs",
                'objectives' => "• Accueillir, informer et accompagner des visiteurs\n• Concevoir et animer un circuit touristique\n• Présenter le patrimoine, l'histoire et la culture d'un territoire\n• Gérer un groupe de visiteurs en toute sécurité\n• Prendre la parole en public avec aisance\n• Mettre en pratique ses compétences sur le terrain pendant 6 mois",
                'career_prospects' => "• Guide touristique\n• Guide culturel\n• Accompagnateur touristique\n• Animateur touristique\n• Agent d'excursion\n• Prestataire touristique",
                'order' => 9,
            ],
            [
                'name' => 'Formation courte en Restauration',
                'code' => 'FC-REST',
                'diploma' => null,
                'specialty_override' => 'Restauration',
                'diploma_recognition' => 'Attestation',
                'level' => 'Sans diplôme préalable',
                'duration' => '4 à 6 mois',
                'description' => "Cette formation courte permet d'acquérir rapidement des compétences pratiques et de découvrir les exigences des métiers de la restauration. Elle est particulièrement adaptée aux personnes souhaitant apprendre un métier concret en quelques mois et intégrer rapidement le monde professionnel.\n\nLa pédagogie est axée sur la pratique : cuisine, préparation des produits, service et hygiène, dans des conditions proches de la réalité professionnelle.",
                'admission_conditions' => "• Être motivé et intéressé par les métiers de la restauration\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "AU PROGRAMME\n• Bases de la restauration\n• Cuisine\n• Préparation des produits\n• Techniques de service\n• Mise en place\n• Accueil client\n• Hygiène\n• Organisation du travail\n• Entretien du matériel",
                'objectives' => 'Elle est particulièrement adaptée aux personnes qui souhaitent acquérir rapidement des compétences professionnelles et se préparer à intégrer le secteur.',
                'career_prospects' => "• Aide-cuisinier\n• Commis\n• Serveur\n• Employé de restauration\n• Agent polyvalent",
                'order' => 10,
            ],
            [
                'name' => 'Agent de Caisse',
                'code' => 'FC-CAISSE',
                'diploma' => null,
                'specialty_override' => 'Agent de Caisse',
                'diploma_recognition' => 'Attestation',
                'level' => 'Sans diplôme préalable',
                'duration' => '4 à 6 mois',
                'description' => "La formation Agent de Caisse prépare aux activités d'encaissement et à la relation avec la clientèle. Elle permet de développer les compétences indispensables à la gestion des opérations de caisse : rigueur, organisation et sens du service, dans un cadre professionnel exigeant.",
                'admission_conditions' => "• Être motivé et rigoureux, à l'aise avec les chiffres\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "VOUS ALLEZ APPRENDRE\n• Techniques d'encaissement\n• Utilisation des outils de caisse\n• Gestion des paiements\n• Accueil du client\n• Relation clientèle\n• Contrôle des opérations\n• Gestion des erreurs\n• Facturation\n• Organisation du poste de travail\n• Communication professionnelle",
                'objectives' => 'Une compétence pratique pour votre avenir professionnel : rigueur, organisation et sens du service au cœur de la formation.',
                'career_prospects' => "• Agent de caisse\n• Caissier\n• Agent d'encaissement\n• Employé de commerce\n• Caissier en hôtel\n• Caissier en restaurant",
                'order' => 11,
            ],
            [
                'name' => 'Chef de Rang',
                'code' => 'FC-CHEFRANG',
                'diploma' => null,
                'specialty_override' => 'Chef de Rang',
                'diploma_recognition' => 'Attestation',
                'level' => 'Sans diplôme préalable',
                'duration' => '4 à 6 mois',
                'description' => "La formation Chef de Rang est destinée aux personnes souhaitant se professionnaliser dans le service en salle et développer les compétences nécessaires à la qualité du service et à la satisfaction de la clientèle.\n\nElle développe l'élégance, l'organisation, la rapidité et le sens du service qui caractérisent les métiers de la salle.",
                'admission_conditions' => "• Être motivé par les métiers du service en salle\n• Avoir une bonne présentation et le sens du contact\n• Fournir un dossier d'inscription complet\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "VOUS ALLEZ APPRENDRE\n• Organisation du service\n• Mise en place\n• Accueil des clients\n• Prise de commande\n• Techniques de service\n• Présentation des plats\n• Service des boissons\n• Débarrassage\n• Relation clientèle\n• Gestion des situations clients\n• Travail en équipe",
                'objectives' => 'Les qualités développées : élégance, organisation, rapidité, communication, sens du service et professionnalisme.',
                'career_prospects' => "• Chef de rang\n• Serveur qualifié\n• Responsable de salle\n• Maître d'hôtel, selon l'expérience et l'évolution professionnelle",
                'order' => 12,
            ],
            [
                'name' => 'Certificat de Spécialité — Cuisine',
                'code' => 'CS-CUISINE',
                'diploma' => 'CS',
                'specialty_override' => 'Cuisine',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Sans diplôme préalable',
                'duration' => '6 mois à 1 an',
                'description' => "Cette formation est destinée aux personnes souhaitant développer leurs compétences pratiques dans le domaine de la cuisine et acquérir une spécialisation professionnelle reconnue par un diplôme d'État.",
                'admission_conditions' => "• Être motivé et intéressé par les métiers de la cuisine\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "AU PROGRAMME\n• Préparation des produits\n• Techniques de découpe\n• Techniques de cuisson\n• Sauces\n• Garnitures\n• Entrées\n• Plats\n• Desserts\n• Dressage\n• Organisation du poste\n• Hygiène et sécurité",
                'objectives' => 'Faites de votre savoir-faire culinaire une compétence professionnelle reconnue.',
                'career_prospects' => "• Cuisinier\n• Commis de cuisine\n• Aide-cuisinier\n• Chef de partie\n• Cuisinier en hôtel\n• Restaurant\n• Traiteur",
                'order' => 13,
            ],
            [
                'name' => 'Certificat de Spécialité — Pâtisserie',
                'code' => 'CS-PATISS',
                'diploma' => 'CS',
                'specialty_override' => 'Pâtisserie',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Sans diplôme préalable',
                'duration' => '6 mois à 1 an',
                'description' => 'Ce certificat permet de faire de votre passion pour la pâtisserie une véritable compétence professionnelle. Il développe un savoir-faire spécialisé et familiarise les apprenants avec les techniques professionnelles de préparation et de présentation.',
                'admission_conditions' => "• Être motivé et intéressé par les métiers de la pâtisserie\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "AU PROGRAMME\n• Préparation des pâtes\n• Crèmes et garnitures\n• Tartes\n• Gâteaux\n• Entremets\n• Décoration\n• Dressage\n• Techniques de finition\n• Hygiène\n• Organisation du travail",
                'objectives' => 'Votre créativité peut devenir votre métier : développer un savoir-faire spécialisé en pâtisserie, de la préparation à la présentation.',
                'career_prospects' => "• Pâtissier\n• Aide-pâtissier\n• Commis pâtissier\n• Employé en pâtisserie\n• Pâtissier en hôtel\n• Traiteur\n• Entrepreneur",
                'order' => 14,
            ],
            [
                'name' => 'Certificat de Spécialité — Restauration',
                'code' => 'CS-REST',
                'diploma' => 'CS',
                'specialty_override' => 'Restauration',
                'diploma_recognition' => "Diplôme d'État",
                'level' => 'Sans diplôme préalable',
                'duration' => '6 mois à 1 an',
                'description' => 'Une formation pratique pour maîtriser les fondamentaux de la restauration. Cette certification permet de développer des compétences professionnelles dans les principaux domaines du métier : cuisine, service, accueil et organisation.',
                'admission_conditions' => "• Être motivé et intéressé par les métiers de la restauration\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "AU PROGRAMME\n• Techniques de restauration\n• Cuisine\n• Service en salle\n• Mise en place\n• Arts de la table\n• Accueil\n• Service des boissons\n• Hygiène\n• Organisation du travail\n• Relation clientèle",
                'objectives' => 'Faites de votre savoir-faire culinaire une compétence professionnelle transversale, alliant cuisine, service et accueil.',
                'career_prospects' => "• Serveur\n• Cuisinier\n• Commis\n• Employé de restauration\n• Agent polyvalent\n• Personnel hôtelier\n• Traiteur",
                'order' => 15,
            ],
            [
                'name' => 'Barista',
                'code' => 'FC-BARISTA',
                'diploma' => null,
                'specialty_override' => 'Barista',
                'diploma_recognition' => 'Attestation',
                'level' => 'Sans diplôme préalable',
                'duration' => '4 à 6 mois',
                'description' => "La formation Barista initie aux techniques du café et à l'art de la préparation des boissons chaudes et froides. Elle permet de développer un savoir-faire recherché dans les coffee shops, hôtels et restaurants qui proposent une offre café de qualité.",
                'admission_conditions' => "• Être motivé et intéressé par les métiers du café et du service\n• Fournir un dossier d'inscription complet\n• Accessible sans diplôme préalable\n\nPièces à fournir : pièce d'identité, dernier diplôme ou certificat si disponible, photos d'identité et formulaire d'inscription.",
                'program' => "VOUS ALLEZ APPRENDRE\n• Connaissance du café\n• Techniques d'extraction\n• Préparation de l'espresso\n• Préparation des boissons\n• Techniques de lait et présentation\n• Entretien du matériel",
                'objectives' => "Maîtriser les techniques professionnelles de préparation du café, de l'extraction à la présentation.",
                'career_prospects' => "• Barista\n• Serveur spécialisé café\n• Employé de coffee shop\n• Personnel hôtelier\n• Entrepreneur",
                'order' => 16,
            ],
        ];

        foreach ($catalog as $data) {
            Formation::updateOrCreate(['code' => $data['code']], $data);
        }
    }
}
